blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include,url
from django.contrib import admin
from django.views.generic import TemplateView

from accounts.views import (
    login_view,
    register_view,
    logout_view)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace = "comments")),
    url(r'^register/',register_view,name = "register"),
    url(r'^login/',login_view,name = "login"),
    url(r'^logout/',logout_view,name = "logout"),
    url(r'^', include("posts.urls", namespace = "posts")),

    # url(r'^post_count','django.views.generic.simple.direct_to_template',{'template':'post_count.html'})
    
    url(r'^aboutus',TemplateView.as_view(template_name='static_about.html'),name="aboutus"),
    url(r'^contactus',TemplateView.as_view(template_name='static_contactus.html'),name="contactus"),
    url(r'^overview',TemplateView.as_view(template_name='static_overview.html'),name="overview"),
    url(r'^categories',TemplateView.as_view(template_name='static_categories.html'),name="categories"),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	fullcount_view,
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)
# from .views import *

urlpatterns = [
	url(r'^$', post_list,name = "list"),
    url(r'^create/$', post_create),
    url(r'^full_count/$',fullcount_view,name = "full_count"),

    url(r'^(?P<slug>[\w-]+)/$', post_detail, name ="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update,name = "update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    ]

comments/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.


class CommentManager(models.Manager):
	def all(self):
		qs = super(CommentManager,self).filter(parent = None)
		return qs

	def filter_by_instance(self,instance):
		content_type = ContentType.objects.get_for_model(instance.__class__)
		obj_id = instance.id
		qs = super(CommentManager,self).filter(content_type = content_type , object_id = obj_id).filter(parent = None)
		return qs


class Comment(models.Model):
	user 	 = models.ForeignKey(settings.AUTH_USER_MODEL , default = 1)
	# post	 = models.ForeignKey(Post)
	
	content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
	object_id = models.PositiveIntegerField()
	content_object = GenericForeignKey('content_type', 'object_id')
	parent = models.ForeignKey("self",null = True,blank = True)

	content	 = models.TextField()
	timestamp= models.DateTimeField(auto_now_add = True)

	objects = CommentManager()

	class Meta:
		ordering = ["-timestamp"]

	def __unicode__(self):
		return str(self.user.username)

	def __str__(self):
		return str(self.user.username)	

	def get_absolute_url(self):
		return reverse("comments:thread",kwargs= {"id": self.id})

	def get_delete_url(self):
		return reverse("comments:delete",kwargs= {"id": self.id})		

	def children(self):  #replies
		return Comment.objects.filter(parent = self)

	@property
	def is_parent(self):
		if self.parent is not None:
			return False
		return True		

posts/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from markdown_deux import markdown
from comments.models import Comment
from .utils import get_read_time

# Create your models here.

class PostManager(models.Manager):
	def active(self,*args,**kwargs):
		return super(PostManager,self).filter(draft = False).filter(publish__lte=timezone.now())
# super(PostManager,self) is similar to Post.objects.all()

def upload_location(instance , filename):
	return "%s/%s" %(instance.slug,filename)
	# filebase,extension = filename.split(".")   saving as id/id.jpg
	# return "%s/%s" %(instance.id,instance.id,extension)



class Post(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL , default = 1)
	title = models.CharField(max_length = 120)
	slug = models.SlugField(unique = True)
	image = models.ImageField(upload_to = upload_location,
		null = True , 
		blank = True,
		width_field = "width_field",
		height_field = "height_field")
	height_field = models.IntegerField(default = 0)
	width_field = models.IntegerField(default = 0)
	content = models.TextField()
	draft = models.BooleanField(default = False)
	publish = models.DateField(auto_now = False , auto_now_add = False)
	read_time = models.IntegerField(default = 0) #models.TimeField(null = True , blank = True)
	updated = models.DateTimeField(auto_now = True , auto_now_add = False)
	timestamp = models.DateTimeField(auto_now = False , auto_now_add = True)

	objects = PostManager()


	def __unicode__(self):
		return self.title	

	def get_absolute_url(self):
		return reverse("posts:detail",kwargs={"slug":self.slug})
		# return "/posts/%s/" %(self.id)

	class Meta:
		ordering = ["-updated","-timestamp",]

	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content) 
		return mark_safe(markdown_text)

	@property	
	def get_content_type(self):
		instance = self
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type

	@property	
	def comments(self):
		instance = self
		qs = Comment.objects.filter_by_instance(instance)
		return qs


def create_slug(instance , new_slug = None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Post.objects.filter(slug = slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug,qs.first().id)
		return create_slug(instance,new_slug = new_slug)	
	return slug	 

def pre_save_post_reciever(sender,instance,*args,**kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)

	if instance.content:
		html_string = instance.get_markdown()
		read_time_var = get_read_time(html_string)
		instance.read_time = read_time_var

pre_save.connect(pre_save_post_reciever,sender = Post)

posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post

class PostForm(forms.ModelForm):
	content = forms.CharField(widget = PagedownWidget(show_preview = False))
	publish = forms.DateField(widget = forms.SelectDateWidget)
	class Meta:
		model = Post
		fields =[
		"title",
		"content",
		"image",
		"draft",
		"publish",
		
		]

posts/views.py
from urllib import quote_plus
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostForm
from .models import Post


# Create your views here.
def fullcount_view(request):
	qs = Post.objects.all()
	context = {
	"allpost":qs,
	"post_count":Post.objects.count,
	}
	return render(request,"full_count.html",context)

def post_create(request):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	form = PostForm(request.POST or None,request.FILES or None)

	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		# print form.cleaned_data.get("title")
		instance.save()
		messages.success(request,"Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())	
	# if request.method == "POST":
	# 	print request.POST.get("content")
	# 	print request.POST.get("title")
	context = {
	"form":form
	}
	return render(request,"post_form.html",context)


def post_detail(request,slug=None):
	# instance = Post.objects.get(id = 1)
	instance = get_object_or_404(Post,slug = slug)
	if instance.draft or instance.publish > timezone.now().date():
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404
	share_string = quote_plus(instance.content)
	
	# print(get_read_time(instance.content))
	# print(get_read_time(instance.get_markdown()))
	
	initial_data = {
		"content_type":instance.get_content_type,
		"object_id":instance.id
	}

	form = CommentForm(request.POST or None,initial = initial_data)
	if form.is_valid() and request.user.is_authenticated():
		# print(form.cleaned_data)
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model = c_type)
		obj_id = form.cleaned_data.get("object_id")
		content_data = form.cleaned_data.get("content") 
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(id = parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()

		new_comment,created = Comment.objects.get_or_create(
							user = request.user,
							content_type = content_type,
							object_id = obj_id,
							content = content_data,
							parent = parent_obj,
							)
		
		return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
	
	comments = instance.comments #Comment.objects.filter_by_instance(instance)


	context = {
	"title":instance.title,
	"instance":instance,
	"share_string":share_string,
	"comments":comments,
	"comment_form":form,
	}
	return render(request,"post_detail.html",context)


def post_list(request):
	today = timezone.now().date()
	queryset_list = Post.objects.active()#.order_by("-timestamp")
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()
	
	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
			Q(title__icontains=query) |
			Q(content__icontains=query) |
			Q(user__first_name__icontains=query) |
			Q(user__last_name__icontains=query)
			).distinct()
	paginator = Paginator(queryset_list, 5) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
	# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
	# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)

	context = {
		"object_list": queryset,
		"page_request_var":page_request_var,
		"today": today,
	}

	# if request.user.is_authenticated():
	# 	context = {
	# 	"title":"My User List"
	# 	}

	# else:	
	# 	context = {
	# 		"title":"List"
	# 	}

	return render(request,"post_list.html",context)



def post_update(request,slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post,slug = slug)
	form = PostForm(request.POST or None,request.FILES or None,instance = instance)

	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		#message success
		messages.success(request,"<a href=# >Item</a> Saved",extra_tags = "html_safe")
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
	"title":instance.title,
	"instance":instance,
	"form":form,
	}
	return render(request,"post_form.html",context)



def post_delete(request,slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post,slug = slug)
	instance.delete()
	messages.success(request,"Successfully Deleted")
	return redirect("posts:list")

templates/base.html
{% load staticfiles %}
<!--DOCTYPE HTML-->

<html>

<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>{% block head_title %} The New Blog {% endblock head_title %}</title>

{% include 'head_css.html' %}


<style>
{% block style %}
{% endblock style %}
</style>

{% block head_extra %}

{% endblock head_extra %}
</head>

<body>

		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.11';
		fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>

{% include "navbar.html" %}	


<div class = "page-wrap">
<div id="page-content-wrapper" style="min-height: 100%">	
    <div id="wrapper" >
   
        <!-- Sidebar -->

        <div id="sidebar-wrapper" >
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                {% if not instance %}
						<a href="{% url 'posts:list' %}" style="font-family: 'Pacifico', cursive;">
                        HomePage
						</a>
                {% else %}
                {% block post_detail_link %}

				{% endblock post_detail_link %}
              	{% endif %}
                </li>
                <li>
                    <a href="{% url 'posts:list' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'posts:full_count' %}">Posts</a>
                </li>
                <li>
                    <a href="{% url 'aboutus'%}">About</a>
                </li>
                <li>
                    <a href="{% url 'contactus'%}">Contact</a>
                </li>
                <li>
                    <a href="{% url 'overview'%}">Overview</a>
                </li>
                <li>
                    <a href="{% url 'categories'%}">Categories</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        
            <div class="container-fluid">
                {% include "messages_display.html" %}


<div class = "container">
<a href="#menu-toggle" class="btn btn-secondary" id="menu-toggle">
	<i class="fa fa-sliders" aria-hidden="true"></i>
	<!-- <span></span>
	<span></span>
	<span></span> -->
</a>
	
<div class = "content">
{% block content %}
	
{% endblock content %}
</div>
<br/>
</div>
   
    
            </div>

        <!-- /#page-content-wrapper -->

</div>
	
            


    </div>
    
  <!-- <footer class="footer">
      <div class="container">
        <span id="id1">Place stickky footer content here.</span>
      </div>
    </footer> -->

</div>
 <!-- <footer class="py-4 bg-dark site-footer">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      
    </footer> -->
<!-- Footer -->
  




{% include 'javascript.html' %}

<script type="text/javascript">
	$(document).ready(function(){
			$(".content-markdown").each(function(){
			var content = $(this).text()
			// console.log(content)
			var markedContent = marked(content)
			// console.log(markedContent)
			$(this).html(markedContent)
		})
	$(".post-detail-item img").each(function(){
		$(this).addClass("img-fluid")
		})
		
		var contentInput = $("#id_content");
		
		function setContent(value) {
			// body...
			var markedContent = marked(value)
			$("#preview-content").html(markedContent)
			$("#preview-content img").each(function(){
				$(this).addClass("img-fluid")
			})
		}
		setContent(contentInput.val())
		contentInput.keyup(function(){
			var newContent = $(this).val()
			setContent(newContent)
		})
		var titleInput = $("#id_title");
		
		function setTitle(value){
			$("#preview-title").text(value)
		}
		setTitle(titleInput.val())
		titleInput.keyup(function(){
			var newTitle = $(this).val()
			setTitle(newTitle)
		})
		$(".comment-reply-btn").click(function(event){
			event.preventDefault();
			$(this).parent().next(".comment-reply").fadeToggle();
		})
		//preview-title
		//preview-content
		
	})
</script>
 <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>


</html>

templates/comment_thread.html
 {% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title  }} | {{ block.super }}
{% endblock head_title %}



{% block content %}



<div class = "col-sm-6 offset-sm-3">
			

				<blockquote class="blockquote blockquote-reverse">
					<p class="mb-0">{{comment.content}}</p>
					<footer class="blockquote-footer"><cite title="Source Title"> via {{comment.user}} </cite>| {{comment.timestamp|timesince}} ago | {% if comment.children.count %}{{comment.children.count}} comment{% if comment.children.count > 1 %}s{% endif %}{% endif %} | {% if request.user == comment.user %}<a href="{{ comment.get_delete_url }}">Delete</a>{% endif %}</footer>
					<br/>
				<hr/>
					<br/>
						<div>
							{% for child_comment in comment.children %}

							<blockquote class="blockquote text-right">
							<p class="mb-0">{{child_comment.content}}</p>
							<footer class="blockquote-footer"><cite title="Source Title"> via {{child_comment.user}} </cite> | {{child_comment.timestamp|timesince}} ago | {% if request.user == child_comment.user %}<a href="{{ child_comment.get_delete_url }}">Delete</a>{% endif %} </footer>
							</blockquote>


							{%  endfor %}


							{% if request.user.is_authenticated %}
								<form method = "POST" action = ".">{% csrf_token %}
									{{ form|crispy }}
									<input type = "hidden" name = "parent_id" value = "{{ comment.id }}">
									<input type = "submit" value = "Reply">
								</form>
							{% else %}
								<p> You musty <a href = "{% url 'login' %}">Login</a> to comment </p>
							{% endif %}	
							
						</div>
						<hr/>
				</blockquote>

				
				
</div>


{% endblock %}

templates/confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title  }} | {{ block.super }}
{% endblock head_title %}



{% block content %}



<div class = "col-sm-6 offset-sm-3">
	<h1>Confirm Delete</h1>	

	<form method = "POST" action = ".">{% csrf_token %}

			<p> Are you sure you want to delete "{{object.content}}" </p>
			<input type = "submit" value = "Confirm" class = "btn btn-warning">
			<a href = "{{ object.get_absolute_url }}" class = "btn btn-default">cancel</a>
	</form>
						
		
</div>


{% endblock %}

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<!-- {{ block.super }} -->

<div class = "col-sm-6 offset-sm-3">

	<h1>{{ title }}</h1>

	<hr/>

	<form method = "POST" action = " " enctype = "multipart/form-data"> {% csrf_token %}
	{{ form|crispy }}
	<input class = "btn btn-success" type="submit" value="{{ title }}">
	</form>

</div>
</div>
{% endblock content %}

templates/full_count.html
{% extends "base.html" %}


{% block content %}


<p class = "lead"> Total Posts : <strong>{{ post_count }}</strong></p>
<hr class = "stylehr"/>
<br/>
<br/>

<table class="table table-striped table-inverse">
  <thead>
    <tr>
      <th>Posts :</th> 
    </tr>
  </thead>
  <tbody>
{% for obj in allpost %}
<tr>
		<td><a href = "{{ obj.get_absolute_url }}">{{ obj.title }}</a></td>
</tr>		
{% endfor %}


</tbody>
</table>



<!-- 
Copy
<table class="table table-striped table-inverse">
  <thead>
    <tr>
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Username</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry</td>
      <td>the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>

 -->


{% endblock %}

templates/messages_display.html
{% if messages %}
	<div class = "messages">
		
			<ul class="messages">
			    {% for message in messages %}
			    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
			    {% endfor %}
			</ul>

	</div>
{% endif %}

templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title  }} | {{ block.super }}
{% endblock head_title %}

{% block post_detail_link %}             
<a href="{{ instance.get_absolute_url }}" style="font-family: 'Pacifico', cursive;">
                        {{ instance.title }}
</a>
{% endblock post_detail_link %}


{% block content %}

<div class = "col-sm-6 offset-sm-3">
	{% if instance.image %}
	<img src="{{ instance.image.url }}" class = "img-fluid"/>
	{% endif %}
	
	<br/>

	<h1>{{title}}<small class = "small-time">{% if instance.draft %} <span style="color: red;">Draft</span> {% endif %} {{instance.publish}}</small></h1>

	<p> Read time : <!-- {% if instance.read_time < 01 %} < 1 minute {% else %}  -->{{ instance.read_time }} minutes<!-- {% endif %} --><!-- {% if instance.read_time|time:"i" <= "01" %} < 1 minute {% else %} {{ instance.read_time|time:"i" }} minutes {% endif %} --> (approx.)</p>

	{% if instance.user.get_full_name %}
	<p>Author : {{ instance.user.get_full_name }}</p>
	{% endif %}
<!-- {{ instance.content|truncatechars:20|urlify }}<br/>
{{ share_string }} -->
<!-- {{request.build_absolute_uri}} -->
<p>
	<div class="fb-like" data-href={{request.build_absolute_uri}} data-layout="button_count" data-action="like" data-size="large" data-show-faces="false" data-share="true"></div>
	</p>

<hr/>
<!-- 	<p>
		<a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
		Facebook
		</a>

		<a href="https://twitter.com/home?status={{ instance.content|truncatechars:80|urlify }}%20{{request.build_absolute_uri}}">
		Twitter
		</a>

		<a href='https://plus.google.com/share?url=http://codingforentrepreneurs.com'></a>

		<a href="https://www.linkedin.com/shareArticle?mini=true&url=http://swiftforentrepreneurs.com/&title={{ instance.title }}&summary={{ share_string }}&source={{request.build_absolute_uri}}">
		Linkedin
		</a>

		<a href="http://www.reddit.com/submit?url={{request.build_absolute_uri}}/&title={{ share_string }}">Reddit</a>
	</p>
 -->	
 <div class="row">
 <div class = "col-sm-12">
 <div class = "post-detail-item">{{instance.get_markdown}}</div>	
 			<!-- {{instance.comments.all}} -->
			<hr/>
			<div>
			<p class = "lead"><b>Comments : </b></p>
			<!-- area where new comments are made -->
			{% if request.user.is_authenticated %}
			<form method = "POST" action = ".">{% csrf_token %}
				{{ comment_form|crispy }}
				<input type = "submit" value = "Post Comment">
			</form>
			{% else %}
				<p> You must <a href="{% url 'login' %}">Login</a> to comment </p>
			{% endif %}	

				<div class="collapse" id="collapseExample">
				<div class="card card-body">
				You Must be Logged in before you can comment ..
				Please <a>Login</a> Here if you wish to proceed   :)
				</div>
				</div>
				
				{% for comment in comments %}

				<blockquote class="blockquote blockquote-reverse">
					<p class="mb-0">{{comment.content}}</p>
					<footer class="blockquote-footer"><cite title="Source Title"> via {{comment.user}} </cite>| {{comment.timestamp|timesince}} ago | {% if comment.children.count %}{{comment.children.count}} comment{% if comment.children.count > 1 %}s{% endif %}{% endif %}{% if request.user.is_authenticated %}<a href = "#" class = "comment-reply-btn"> Reply</a>{% else %}<a href = "#collapseExample" data-toggle="collapse" class = "comment-reply-btn"> Reply</a>{% endif %}<a href='{{ comment.get_absolute_url }}' class = ""> Thread</a></footer>
				
<!-- data-toggle="collapse"
href="#collapseExample"
<div class="collapse" id="collapseExample">
  <div class="card card-body">
    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
  </div>
</div> -->


						<div class = "comment-reply">
							{% for child_comment in comment.children %}

							<blockquote class="blockquote text-right">
							<p class="mb-0">{{child_comment.content}}</p>
							<footer class="blockquote-footer"><cite title="Source Title"> via {{child_comment.user}} </cite> | {{child_comment.timestamp|timesince}} ago )</footer>
							</blockquote>


							{%  endfor %}

							<!-- child comment form -->
						{% if request.user.is_authenticated %}
								<form method = "POST" action = ".">{% csrf_token %}
									{{ comment_form|crispy }}
									<input type = "hidden" name = "parent_id" value = "{{ comment.id }}">
									<input type = "submit" value = "Reply">
								</form>
						{% else %}
							<p> You must Login to comment </p>
						{% endif %}	
						</div>
						<hr/>
				</blockquote>
					
				
				{% endfor %}
				
				<!-- {{ instance.comment_set.all }} -->
				
			<!-- <div class="fb-comments" data-href={{request.build_absolute_uri}} data-numposts="5"></div> -->

</div>
</div>
</div>


{% endblock %}

templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
<!-- {% load staticfiles %} -->


	{% block head_extra %}
		{{ form.media }}
	{% endblock head_extra %}

{% block content %}
<!-- {{ block.super }} -->
<div class = "row">
<div class = "col-sm-6">
<h1>Preview : </h1>
<hr/>
<div class = "content-preview">
	<h3 id = "preview-title"></h3>
	<p id = "preview-content"></p>
</div>

</div>

<div class = "col-sm-6">

	<h1>Form :</h1>

	<hr/>

	<form method = "POST" action = " " enctype = "multipart/form-data"> {% csrf_token %}
	{{ form|crispy }}
	<input class = "btn btn-success" type="submit" value="Create Post">
	</form>

</div>
</div>
{% endblock content %}

templates/static_about.html
{% extends "base.html" %}


{% block content %}

	<br/>
	<br/>

	<h5>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</h5>

	<hr class = "stylehr">
	<br/>
	<h2 style = "color:#5D6D7E;"> Developed by Nayan</h2>
	<br/>
	<hr class = "stylehr">
{{ models.Post.count }}


{% endblock %}

templates/static_contactus.html
{% extends "base.html" %}


{% block content %}



<h1>Contact us : </h1>

{{ models.Post.count }}


{% endblock %}

templates/static_overview.html
{% extends "base.html" %}


{% block content %}



<h1>MAde With Django and Bootstrap</h1>

{{ models.Post.count }}


{% endblock %}